clean:
module: "TunnelKit"
author: "Davide De Rosa"
author_url: "https://github.com/passepartoutvpn/tunnelkit"

theme: fullwidth

custom_categories:
    - name: Core
      children:
        - BidirectionalState
        - ConfigurationError
        - DNSProtocol
        - DNSResolver
        - DNSRecord
        - EndpointProtocol
        - IOInterface
        - IPv4Settings
        - IPv6Settings
        - LinkInterface
        - Proxy
        - Session
        - SocketType
        - TunnelInterface
        - IPHeader
    - name: AppExtension
      children:
        - GenericSocket
        - GenericSocketDelegate
        - InterfaceObserver
        - Keychain
        - KeychainError
        - LinkProducer
        - MemoryDestination
        - NETCPSocket
        - NETunnelInterface
        - NEUDPSocket
    - name: Manager
      children:
        - VPN
        - VPNConfiguration
        - VPNProvider
        - VPNProviderIPC
        - VPNStatus
        - NetworkExtensionLocator
        - NetworkExtensionNativeLocator
        - NetworkExtensionTunnelLocator
        - NetworkExtensionVPNConfiguration
        - NetworkExtensionVPNProvider
        - MockVPNProvider
    - name: Protocols/Native
      children:
        - NativeProvider
    - name: Protocols/OpenVPN
      children:
        - OpenVPN
        - OpenVPNError
        - OpenVPNProvider
        - OpenVPNSession
        - OpenVPNSessionDelegate
        - OpenVPNTunnelProvider
